[package]
name = "rust-gba"
version = "0.1.0"
edition = "2021"
resolver = "2"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[profile.release]
opt-level = 3
debug = 2
overflow-checks = true
# lto = true
# codegen-units = 1