[workspace]
members = [
	"emulator-barebones",
	"emulator-core",
	"emulator-egui",
	"emulator-native",
]
resolver = "2"

[profile.release]
opt-level = 3
debug = 2
overflow-checks = true
# lto = true
# codegen-units = 1
