[package]
name = "emulator-core"
version = "0.1.0"
edition = "2021"
resolver = "2"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lazy_static = "1.4.0"
phf = { version = "0.11.1", features = ["macros"] }
regex = "1.6.0"
xxhash-rust = { version = "0.8.5", features = ["xxh3"] }