[package]
name = "emulator-core"
version = "0.2.0"
edition = "2021"
resolver = "2"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.66"
dynasmrt = "1.2.3"
lazy_static = "1.4.0"
log = "0.4.17"
phf = { version = "0.11.1", features = ["macros"] }
regex = "1.7.0"
serde = { version = "1.0.150", features = ["derive"] }
serde_with = "2.1.0"
xxhash-rust = { version = "0.8.6", features = ["xxh3"] }

[dev-dependencies]
criterion = "0.4.0"

[[bench]]
name = "bench_cpu"
harness = false