# This is a basic workflow to help you get started with Actions

name: Run Tests

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  pull_request:

  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build-and-test-ubuntu:
    strategy:
      matrix:
        os:
        - ubuntu-20.04
        - ubuntu-22.04
        - ubuntu-latest

    # The type of runner that the job will run on
    runs-on: ${{ matrix.os }}

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Install build dependencies required to build the emulator.
      - name: Install build dependencies
        run: |
          sudo apt update -y && \
          sudo apt install -y \
            libasound2-dev \
            libatk1.0-dev \
            libgtk-3-dev

      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          default: true

      - name: Check formatting
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --check

      - name: Build project
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --all-targets

      - name: Run tests
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --release --all-targets

  build-and-test-mac:
    strategy:
      matrix:
        os:
        - macos-11
        - macos-12
        - macos-latest

    # The type of runner that the job will run on
    runs-on: ${{ matrix.os }}

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          default: true

      - name: Check formatting
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --check

      - name: Build project
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --all-targets

      - name: Run tests
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --release --all-targets
